server:
  port: 8080
mysql:
  username: root
  password: "123456"
  host: 192.168.56.101
  port: 3306
  dbname: my_page
  timeout: 10
# rabbitmq:
#     enable: false
#     username: guest
#     password: guest
#     host: 192.168.56.101
#     port: 5672
