server:
  port: 8080
mysql:
  enable: false
  username: root
  password: "123456"
  host: 192.168.56.101
  port: 3306
  dbname: my-page
  timeout: 10
mongo:
  enable: true
  host: 192.168.56.101
  port: 27017
  username: my-page
  password: "123456"
  dbname: my-page
